export enum Streams {
  COLLABORATORS = 400,
  METADATA,
  DOCUMENT_CONTENT,
  CURSOR,
  CAUSALNODE
}

export enum StreamsSubtype {
  COLLABORATORS_JOIN = 100,
  COLLABORATORS_LOCAL_UPDATE,
  DOCUMENT_OPERATION,
  DOCUMENT_QUERY,
  DOCUMENT_REPLY,
  METADATA_TITLE,
  METADATA_FIXDATA,
  METADATA_LOGS,
  METADATA_PULSAR,
  CRYPTO,
  CURSOR,
  CAUSAL_SHARD= 1000, ////RAJOUT
  CAUSAL_ATTEST=1001, ////RAJOUT
  CAUSAL_REVEAL=1002, ////RAJOUT
  CAUSAL_WITNESS=1003,
  CAUSAL_CONFIRM=1004,
}

export interface StreamId {
  type: Streams
  subtype: StreamsSubtype
}
